[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chopsticks_optimal_play"
version = "0.1"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
